### ISSUE TITLE
[Feature] Edit none VSLook themes

### ISSUE THREAD

**Issue by mustafaabobakr** [sudoaugustin/vslook#1]
It would be awesome to edit any theme user prefers or already use. 
It edits it on the fly, BUT cannot save changes!

**Comment by sudoaugustin** [comment]
I replied u [here](https://marketplace.visualstudio.com/items?itemName=sudoaugustin.vslook&ssr=false#review-details). 

It's a nice idea too. Your actual problem is not able to customize with VSLook upon your favorite theme. If so allowing to import your favorite theme with a command and overwrite the VSLook theme file will solve the problem?

**Comment by mustafaabobakr** [comment]
> I replied u [here](https://marketplace.visualstudio.com/items?itemName=sudoaugustin.vslook&ssr=false#review-details).
> 
> It's a nice idea too. Your actual problem is not able to customize with VSLook upon your favorite theme. If so allowing to import your favorite theme with a command and overwrite the VSLook theme file will solve the problem?

YES please

**Comment by sudoaugustin** [comment]
Sure I do it soon and inform u here. Thx for your feedback.

**Comment by alfuken** [comment]
A related suggestion: load VSLook colours from a VSCode theme as a preset. For example, I love LAZY theme, but I would like to change a few bits and bobbles. Reproducing the whole theme from zero using VSLook's controls is really a PITA. Would be awesome if I could say "Load colours from this theme", and continue from there.

**Comment by sudoaugustin** [comment]
@mustafaabobakr @alfuken  
Feature added [here](https://github.com/sudoaugustin/vslook#-clone-theme). Try `VSLook: Clone`. 
If you find any bugs, please report 🙏 .
